### ISSUE TITLE
Can we use a remote gitolite server ?

### ISSUE THREAD

**Issue by lutinwood** [kubitron/redmine_git_hosting#13]
Hi, 
I'm trying to get the ssh branch working to allow me to use a different server to host git  than the one hosting redmine. 

I'm using the ssh brach for this purpose ...But when I create new project the repository is not created ... I'm looking trough redmine/log/development.log (mostly db calls) , /var/log/auth.log (on local and on my remote gitoliteserver) but I get not any informations about what happen or what could have failed .. 

where could I track to get more infos ... 

my gitolite is working fine on command line , 

I've got a different ssh key for the user (the one than can access to the server on ssh with git user ) and the git user (the one than can clone gitolite-admin) both private key are on my (redmine/.ssh/) with owner www-data:www-data .. 

I've tried with ssh branch from your git and from the ericpaulbishop one .. 

I will understand than you've decided to not maintained that branch anymore ! 

I've read the ssh branch doc and it says that it might failed if I use a remote. 

just to know if I should avoid to use  a different server to host my automatic created repositories..  

thanks...

**Comment by kubitron** [comment]
Hm.... I can't say that I've every used or maintained that branch (I realize that github is a bit confusing as to who maintains which branches, but I didn't start maintaining my fork and branches until last November; it seems that the sshe branch hasn't been updated since last June).  Where is the branch documentation that you are reading?  (just out of curiosity)?

On quick thought, there are a number of operations that the primary branches of this plugin performs directly on the repository (via sudo), so the functionality of a version of the plugin that worked on a remote gitolite repository would be limited.

**Comment by lutinwood** [comment]
Hi , 

I found the documentation on the ssh branch of your repository and you can see it on github there https://github.com/kubitron/redmine_git_hosting/tree/ssh. 

Ok thanks for the clearance. I think I 'll keep my git hosting on the same server than my redmine install. 

thanks for your time I close this issue..

**Comment by kubitron** [comment]
Ok.  In principle, it might be possible to make this work well, but it would require a bunch of hacking to make it work.  You could post it as a feature request, but I'm not sure when I would be able to get to it next.

At this point, it is definitely a good idea to stay on the same server for both Redmine and Gitolite....
