### ISSUE TITLE
update_repositories does not update the config

### ISSUE THREAD

**Issue by anarcat** [kubitron/redmine_git_hosting#29]
Running the following command didn't update the gitolite config files:

```
redmine@apps:/usr/share/redmine$ env X_DEBIAN_SITEID=koumbit RAILS_ENV=production rake redmine_git_hosting:update_repositories
```

The keys are updated, but not `conf/gitolite.conf`. The `/tmp/redmine_git_hosting/gitolite/gitolite-admin` doesn't show the changes either.

I need to regenerate the gitolite.conf file to take into account all the repositories since I migrated from an older version.

**Comment by kubitron** [comment]
Can you tell me more?  This is supposed to work.  Did you run this command as your web user (rather than as root)?

Are you using Redmine 1.1?

Are there any errors in log/production.log?  Also, what does the log entry look like caused by the update_repositories operation?  Should be something kinda like this:

<pre>
Processing SysController#fetch_changesets (for 128.32.37.213 at 2012-03-14 15:00:01) [GET]
  Parameters: {"key"=>"elsP2QBqLKh6UclLlP2B"}
Executing RESYNC_ALL operation on gitolite configuration
Fetching changes from gitolite-admin repository to /tmp/redmine_git_hosting/git-tess/gitolite-admin
Our hook is already installed
Completed in 1782ms (View: 1, DB: 72) | 200 OK [https://tessellation.cs.berkeley.edu/redmine/sys/fetch_changesets?key=elsP2QBqLKh6UclLlP2B]
</pre>


See if you can find the entry (with a RESYNC_ALL) that was caused by your update_repositories command.  It should show a bunch of keys being added, if that is what happened.

Does the `rake redmine_git_hosting:fetch_changesets` work any better or worse?  Can you show me your file and tell me what is missing?

**Comment by anarcat** [comment]
I can certainly tell you more! Thanks for checking in. :)

I am using Redmine 1.1 now, i just double-checked:

```
Redmine 1.1.2.stable (MySQL)
```

There is no log entry for the command at all:

```
grep RESYNC_ALL /var/log/redmine/koumbit/production.log
```

fetch_changesets is not doing any better.

the config file is missing most projects. The only one that are present are the ones where i manually went into the members list for that project and edited myself.

**Comment by anarcat** [comment]
Oh and sorry for the multiple issues in one bunch, I only had time to look at all this today. If you have to prioritise, I would say the one here is the most urgent for us. :)

**Comment by kubitron** [comment]
Ok.  I can't do it right now, but I'll try to look tonight.

The fact that you aren't getting any signs of a RESYNC_ALL is highly suspicious.

**Comment by anarcat** [comment]
anything new i can try here? is there a flag i can pass on the rake commandline to have more debugging messages?

**Comment by kubitron** [comment]
Sorry.  I went back to my Redmine 1.1 environment and discovered that the log wasn't being flushed when you run rake tasks.  For now, I simply brute-forced it in the rake calls so that there are log entries.

That being said, pull the testing branch (one commit) and run `rake redmine_git_hosting:update_repositories` again.  Tell me what the log says.  There should be a RESYNC_ALL statement in the log (along with everything that follows).

**Comment by anarcat** [comment]
This branch fails with:

```
apps:/usr/share/redmine# sudo -u redmine X_DEBIAN_SITEID=koumbit RAILS_ENV=production rake redmine_git_hosting:update_repositories --trace
(in /usr/share/redmine)
rake aborted!
uninitialized constant Rake::DSL
/usr/lib/ruby/1.8/active_support/dependencies.rb:440:in `load_missing_constant'
/usr/lib/ruby/1.8/active_support/dependencies.rb:80:in `const_missing'
/usr/share/redmine/vendor/plugins/redmine_git_hosting/tasks/redmine_git_hosting.rake:33
/usr/lib/ruby/1.8/active_support/dependencies.rb:145:in `load_without_new_constant_marking'
/usr/lib/ruby/1.8/active_support/dependencies.rb:145:in `load'
/usr/lib/ruby/1.8/active_support/dependencies.rb:521:in `new_constants_in'
/usr/lib/ruby/1.8/active_support/dependencies.rb:145:in `load'
/usr/share/redmine/vendor/rails/railties/lib/tasks/rails.rb:7
/usr/share/redmine/vendor/rails/railties/lib/tasks/rails.rb:7:in `each'
/usr/share/redmine/vendor/rails/railties/lib/tasks/rails.rb:7
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
/usr/share/redmine/Rakefile:10
/usr/lib/ruby/1.8/rake.rb:2383:in `load'
/usr/lib/ruby/1.8/rake.rb:2383:in `raw_load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2017:in `load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2016:in `load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2000:in `run'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:28
apps:/usr/share/redmine#
```

**Comment by anarcat** [comment]
I _think_ this works now, oddly enough: the gitolite.conf was regenerated somehow during my last tests. Even though I do not get logging, it seems that the gitolite.conf was regenerated. I think this is related to #32, which I just worked around manually. My theory is that the hook was crashing without any output due to the corruption of the git_repository_extras table and was simply not getting to the point where it updates the config.

I still think logging should be fixed and at least errors should get to the log. Also: the testing branch breaks 1.1 still. :) So i'll keep this open for now.

**Comment by kubitron** [comment]
Ok.  Pull again and see if you can get a log message out of update_repositories....

**Comment by anarcat** [comment]
Alright, I see the log messages! Everything seems to be alright now, thanks!

**Comment by kubitron** [comment]
Ok.  Keep in mind that the _only_ thing I did was make the log messages visible....

I'm going to commit these changes to the main branch and remove the testing branch.
