### ISSUE TITLE
ActionView::TemplateError (uninitialized constant ApplicationHelper::TabularFormBuilder) on line #9 of vendor/plugins/redmine_git_hosting/app/views/my/account.html.erb

### ISSUE THREAD

**Issue by ghost** [kubitron/redmine_git_hosting#37]
I posted on the incorrect branch.  I'm duplicating it here.

I have this version of redmine checked out, which is 1.3.2+
c17e7e8642140831fa1bbc7bdbd0a9204eb39484

I have this version of kubitron redmine_git_hosting, from about 3/28/2012
fef6fdada3e48d7afa4c9f0714aff7894f47b95b

I'm running Ubuntu Wheezy, testing.  All of the latest binary packages provided by the distribution as well as gems.  In other words the only source packages on my machine are redmine and it's plugins.

When I click on "My Account" I receive the application error, with the below in my redmine log:

``` ruby
Processing MyController#account (for 192.168.20.3 at 2012-04-01 01:37:53) [GET]
  Parameters: {"action"=>"account", "controller"=>"my"}
Rendering template within layouts/base
Rendering my/account

ActionView::TemplateError (uninitialized constant ApplicationHelper::TabularFormBuilder) on line #9 of vendor/plugins/redmine_git_hosting/app/views/my/account.html.erb:
6: <%= error_messages_for 'user' %>
7:
8: <div class="splitcontentleft">
9:      <% labelled_form_for :user, @user, :url => { :action => "account" }, :html => { :id => 'my_account_form' } do |f| %>
10:     <fieldset class="box tabular">
11:             <legend><%=l(:label_information_plural)%></legend>
12:             <p><%= f.text_field :firstname, :required => true %></p>

    vendor/plugins/redmine_git_hosting/app/helpers/application_helper.rb:14:in `labelled_form_for'
    vendor/plugins/redmine_git_hosting/app/views/my/account.html.erb:9
    public/dispatch.fcgi:24
```

I renamed the backward campatility definitions of labelled_form_for and others in app/helpers/application_helper.rb.  Once I did that My Account loaded fine.

**Comment by kubitron** [comment]
Well, you must be running off the trunk.  As it says in the README, this plugin is _NOT_ compatible with the trunk.  You need to pull 1.3-stable instead (i.e. actually 1.3.2, not 1.3.2+).  The problem is that the trunk has a bunch of multi-repository-per-project features, and this version of the plugin doesn't support those features.

That much being said, I can push a fix that will get you past this problem, but you will have a number of other ones, I'm afraid.

**Comment by kubitron** [comment]
I've pushed a proposed patch to my 'testing' branch.  Can you pull from there and see if this particular problem goes away?  Note that there is no guarantee that you won't have a lot of problems with this anyway, since I believe that you pulled from the Redmine trunk instead of 1.3-stable branch.  However, I'd love to see if this patch fixes things for you before you pull the correct version of Redmine....

**Comment by kubitron** [comment]
Actually, I pushed the fix to my master branch, since it should be relatively innocuous. Let me know if the problem goes away (so I can close).

**Comment by ghost** [comment]
Its good, thanks.
