### ISSUE TITLE
unique keys

### ISSUE THREAD

**Issue by gituser** [kubitron/redmine_git_hosting#61]
There is a bug with adding new users to deployment credentials.

If you add the same key with different permissions - redmine will add only permissions from the  first added key.

To reproduce go to project settings  -> repository

Add the same key twice - first with R permissions and second with RW under two different names.

Also, I think redmine_git_hosting allows adding same key over multiple users (not sure, didn't test it yet).

**Comment by kubitron** [comment]
Two comments on this bug:
- This is a general bug with the plugin (pre-deployment credentials), since it lets you put the same key into different user's public key pages and the wrong thing will happen!  (You actually can not have the same key used twice anywhere in a gitolite repo).
- Functionally, it makes no sense to add the same key with different credentials, since permissions are in a strictly inclusive hierarchy (i.e. RW+ includes R functionality). Thus, the "right" thing to do in your case would be to have edited the original deployment credential to turn the "R" into an "RW+".
- The fix to this issue will be to make public keys globally unique in the whole deployment.  I'm assuming that this makes sense to you?

**Comment by gituser** [comment]
> Functionally, it makes no sense to add the same key with different credentials, since permissions are in a strictly >inclusive hierarchy (i.e. RW+ includes R functionality). Thus, the "right" thing to do in your case would be to have >edited the original deployment credential to turn the "R" into an "RW+".

well yes, but what I mean here is deployment shouldn't allow adding the same key, right? it should give a warning that this key was used once.

> This is a general bug with the plugin (pre-deployment credentials), since it lets you put the same key into different >user's public key pages and the wrong thing will happen! (You actually can not have the same key used twice >anywhere in a gitolite repo).

Agree, keys should be unique per user as well as deployment keys

> The fix to this issue will be to make public keys globally unique in the whole deployment. I'm assuming that this >makes sense to you?

So there is no ability to add let's say on 1 deployment key different permissions for different projects?

Let's say I have 1 key and I want to add:

read access on project1
read/write access on project2

etc.. is it possible at all ?

I think key's uniqueness should be checked for specific project only if it makes any sense.

**Comment by kubitron** [comment]
You keep talking about deployment credentials.  I am talking about public keys.  

A deployment credential is a paring of a key and a permission.  If you go to another repo, you will see that you have the option of reusing a key (with the same name) to create a new deployment credential.  You will not be able to create two deployment credentials with the same key name on the same repository (that is currently prevented).

The bug here is allowing the same key text to be represented with a different name.

**Comment by kubitron** [comment]
> The bug here is allowing the same key text to be represented with a different name.

What I mean is that the plugin doesn't make sure that keys are actually unique, just that they have different names.  This is a long-running bug (from before my fork) that should be fixed.

**Comment by gituser** [comment]
Ye, I understand what you're saying, but what I meant earlier is:

1) Keys should be unique for each user in redmine (public key).
2) Deployment keys should be unique for 1 project, i.e. let's say I have 2 deployment keys (one for read-only access _key1_ and for read-write access _key2_) and I want to use same keys for a different project. 
The typical situation: you have multiple projects and want to deploy them on the same server with the same key _key2_ and checkout projects from redmine with _key1_.

I hope you get me this time.

**Comment by kubitron** [comment]
> well yes, but what I mean here is deployment shouldn't allow adding the same key, right? it should give a warning that this key was used once.

Of course.  But, as I mention above, the same warning should be given to a user who tries to add any key that someone else has added before.  This is likely to be a weird warning for a vanilla (inexperienced) user, but the weird behavior that would result if we let it happen would be worse.

I'll think of the best way to fix this.  Probably add an MD5 field to make checking quick...

**Comment by gituser** [comment]
> Of course. But, as I mention above, the same warning should be given to a user who tries to add any key that someone else has added before. This is likely to be a weird warning for a vanilla (inexperienced) user, but the weird behavior that would result if we let it happen would be worse.
> I'll think of the best way to fix this. Probably add an MD5 field to make checking quick... 

I think there is no need for MD5? You just need to extract actual key part without comment at the end and compare it? If I knew ruby I'd write a patch :)

**Comment by kubitron** [comment]
I think we are talking cross-purposes here.

1) If any key in any context is repeated, gitolite breaks.  Thus, keys don't have to be unique just within a given user, but across all users (and cannot even match the gitolite admin key).  This is a long-running bug.  I'll put in a patch to prevent it; it is high time this got fixed.

2) Once you have added a deployment key, you can use it in every repository on the system for which you are a manager (which means ever repo for the administrator); each such deployment credential can have different permissions.  To use a key in another project, just create a new deployment credential and select the existing key from the drop-down instead of "Create new key".  Thus, the current implementation should do what you want already.   Just avoid adding the same physical key multiple times and see if you get all the functionality you need.

Try going to the "my account" page and notice that the keys you create at the same time you create deployment credentials are added to the my account page as "deploy keys".

**Comment by kubitron** [comment]
p.s. the MD5 use is so that I can easily index the keys and make key addition quicker than scanning through all the keys for matches.  

Note that I might as well check some other things about the key format at the same time, so will probably do that.  The latest commit on the testing branch finally allows public key validation errors to be pushed out to the user interface, so I can put in more sophisticated errors than simply "Key Identifier not unique" or "key cannot be blank"...

**Comment by gituser** [comment]
Thanks for this long explanation, much appreciated!

**Comment by kubitron** [comment]
No problem.  Since you are the first user of this feature, you feedback is very helpful.

Modulo this bug, does the deployment credential feature seem to do what you might need?  (I realize that you were not one of the original requesters of this feature -- I took so long to getting it implemented that I may have lost them).

**Comment by gituser** [comment]
> Modulo this bug, does the deployment credential feature seem to do what you might need?

I think yes, I just checked - you can use already added deployment key in any project. That's nice.

**Comment by kubitron** [comment]
Great.  Let me know as you play with it.    I'm going to put a uniqueness fix for public keys in before pushing this to master.  (I also want to hear from another person on the new mirror functionality as well).

I want to push the version number of the plugin and then tackle Redmine 1.4 functionality (although I may try to find out why someone was having problems with Chili 3.3 as well).

**Comment by kubitron** [comment]
Ok.  Pull the top commit on the testing branch.  It validates some properties of keys including global uniqueness.

Let me know what you think... (see if you can break it).

**Comment by kubitron** [comment]
Oops. The uniqueness patch I put up had a bug.  There is a better one there now...

(You may need to do a reset --hard on the last commit, since I replaced it).

**Comment by gituser** [comment]
Hi! Thanks for the note.

I will test soon and report back.

**Comment by kubitron** [comment]
Ok.  Let me know.  I would like to close out this issue.

**Comment by kubitron** [comment]
I am closing out this bug.  It seems to be fixed.  I have migrated patches to master (as part of incrementing to version 0.4.6x).
