### ISSUE TITLE
deselecting default repository doesn't activate Identifier

### ISSUE THREAD

**Issue by gituser** [kubitron/redmine_git_hosting#72]
Here is a first bug:

1) You need to go to the project settings->repositories
2) Create one as a default (which means there is no Identifier)
3) Now try editing it - deselect flag 'default'

Redmine says there should be a unique identifier, but Identifier field is grayed out.. So it's probably possibly to only manually alter.

**Comment by kubitron** [comment]
Not a bug.  A "Feature" of the plugin.  Once you have chosen the identity of the repository (in this case, it will be identified by the name of the project like in < 1.4), it won't change, since it defines the name in gitolite.

Incidentally, blank id=> default, but default does not => blank.  You can construct a first repo with an identifier.

**Comment by kubitron** [comment]
Do other things work?  You can create a default repo with a non-blank identifier -- you just need to create it manually (i.e. not using the automatic creation feature of the plugin).

**Comment by gituser** [comment]
Creating repository works so far, editing too. I didn't test much yet. Need to create a new project and test there.

**Comment by kubitron** [comment]
OK.  Mostly curious whether the repository browsing facilities work for you. (i.e. going to the "repository" link of a project).  One tester having problems...

**Comment by gituser** [comment]
works fine for me.

did your tester have done rake db:migrate_plugins?

because i had problems before issuing this command.

**Comment by kubitron** [comment]
Some more subtle problem.  System probably completely non-usable without db:migrate_plugins...

**Comment by kubitron** [comment]
@gituser, can you re-pull from head of tesitng branch?  I've made some changes that I hope will make this overall more stable.  Hopefully there are no problems that have gotten reintroduced.

**Comment by kubitron** [comment]
Also @gituser -- do you have any comments on the interface?  (i.e. the thing that started this thread)?

**Comment by gituser** [comment]
well, I got your initial reply, so it's a feature rather than a bug. (would be better if it can be changed but i guess it's the redmine thing and you can't do much with it rather than deleting all repos and creating from scratch if you want to change default repository or change repository ID).

about repository browse - it worked well for me I didn't notice any glitches yet.

Repository options: 
adding/deleting/editing repositories worked

I didn't test yet:
Deployment Credentials
Post Receive URLs
Repository Mirrors

Once I test this functionality I will report back.

EDIT: just pulled latest HEAD from testing

EDIT2: just tested creating NEW repository furthermore, added files and tried to navigate in the redmine's repo browser - it works.

P.S. all tests were on:
`
Redmine 1.4.4.stable.10529 (MySQL)
Ruby version    1.8.7 (x86_64-linux)
RubyGems version    1.3.7
Rack version    1.1.3
Rails version   2.3.14
Active Record version   2.3.14
Active Resource version 2.3.14
Action Mailer version   2.3.14
Active Support version  2.3.14
Application root    /var/www/redmine-1.4
Environment production
Database adapter    mysql
Database schema version 20120904060609
`

**Comment by kubitron** [comment]
Great that things seem to be working!  Soon, I would like to export it to master, since the latest commits reflect a fix to something that may actually mess people up a bit on the HEAD of master.   

As for the identifier issue -- it is not strictly a redmine thing -- it is more of a choice about how gitolite repos are named.  The issue of allowing you to change an existing identifier is that it would change the name of the repository in gitolite (because of the explicit mapping between project name/repository identifier => gitolite repo name).   I picked the closest thing that is equivalent to what was there before.

Now, you can turn off the automatic creation of repositories, then create a first repository manually with a non-blank identifier.  Then, you are allowed to make other repos the default, if you wish.  The only constraint is that you cannot change the identifier once the repo is created.  My addition to the picture.

**Comment by kubitron** [comment]
Ok.  @gituser, I'm going to close out this bug.  If you have a feature request to change the multi-repo behavior, then you can register a new issue.
