### ISSUE TITLE
Deleting user's public ssh key

### ISSUE THREAD

**Issue by saric** [kubitron/redmine_git_hosting#86]
When I try to delete user's public ssh key by pressing button "delete" in "Edit existing Public key", it fails, while deleting the same key using "delete" hyperlink is working.

**Comment by kubitron** [comment]
Hm... Works for me.  Does it pop up an "are you sure" dialog?  Do you have javascript enabled?

Which version of redmine are you using again?  Also, can you give me to output of ./script/about?  (go to root of redmine, set RAILS_ENV environment variable, then execute "./script/about".

**Comment by kubitron** [comment]
I am wondering if this problem is related to the configuration issue with apache...

**Comment by kubitron** [comment]
Sorry -- I misunderstood your error.  Can you say more about what happens?  What is the error in the log?  What is the exact behavior?  (And, can you give me the ./script/about information)?  Does "Create" and/or "Cancel" work in that dialog?

I apologize for all the problems that you are having.

**Comment by saric** [comment]
No, I'm testing this without Apache right now.
Using only Nginx+Passenger at the moment.

**Comment by saric** [comment]
Here is the output of script/about:

```
Ruby version              1.8.7 (i386-linux)
RubyGems version          1.3.7
Rack version              1.1.3
Rails version             2.3.14
Active Record version     2.3.14
Active Resource version   2.3.14
Action Mailer version     2.3.14
Active Support version    2.3.14
Application root          /usr/local/src/redmine-1.4.4
Environment               production
Database adapter          mysql
Database schema version   20120904060609

About your Redmine plugins
Redmine Git Hosting Plugin                                      0.5.0x
```

Here is excerpt from log file, when I press "Delete" button:

```
Processing UsersController#edit (for *.*.*.* at 2012-10-17 23:32:29) [GET]
Parameters: {"action"=>"edit", "id"=>"4", "tab"=>"keys", "controller"=>"users", "public_key_id"=>"7"}
Rendering template within layouts/admin
Rendering users/edit
Completed in 289ms (View: 271, DB: 3) | 200 OK [http://redmine/redmine/users/4/edit/public_key/7?tab=keys]

Processing GitolitePublicKeysController#update (for *.*.*.* at 2012-10-17 23:32:50) [PUT]
Parameters: {"action"=>"update", "id"=>"7", "user_id"=>"4", "button_submit_field"=>"true", "tab"=>"keys", "public_key"=>{"title"=>"saric"}, "authenticity_token"=>"...CENSURED...=", "controller"=>"gitolite_public_keys", "save_button"=>"Save", "_method"=>"put"}
Fetching changes from gitolite-admin repository to /tmp/redmine_git_hosting/git/gitolite-admin
Creating MD5 digests for Redmine Git Hosting hook
Digest for post-receive.redmine_gitolite.rb: c9a05723962684b6af4f9b27ca055f71
Our hook is already installed
Completed in 7968ms (View: 3, DB: 37) | 200 OK [http://redmine/redmine/my/public_keys/7?tab=keys&user_id=4]
```

Dialog box is shown asking the question "Are you sure you want to destroy ...?"
"Cancel" and "Save" buttons works as expected, ssh key can't be modified, only ssh key identifier can.

**Comment by kubitron** [comment]
What is a bit weird about the above is that it appears that the JavaScript that is supposed to be invoked to cause the right thing to happen is not happening... Is Javascript enabled?

**Comment by kubitron** [comment]
Also, which browser are you using?

**Comment by saric** [comment]
Google Chrome and Mozilla Firefox with JavaScript enabled.

**Comment by kubitron** [comment]
Hm.... I just tried Chrome (I use Firefox normally) and both seem to work.

Although I realize that your installation seems to have only 1 plugin, is it possible that you have others or other things that might have prevented the proper initialization of javascript on that page?  I am wondering if you could go to edit dialog and send me the page source?  (in firefox it is a right click menu item).

Just so you know, the issue is that Prototype.js (javascript framework used by Rails 2) is unable to distinguish multiple submit buttons in a form properly.  Thus, I added some javascript that takes the clicked button and sets a form variable that indicates which button was pushed.  When working, the log should look like this:

<pre>
Processing GitolitePublicKeysController#update (for *.*.*.* at 2012-10-18 09:25:21) [PUT]
  Parameters: {"public_key"=>{"delete_when_unused"=>"1", "title"=>"My Public Key #1", "key_type"=>"0"}, "_method"=>"put", "id"=>"483", "controller"=>"gitolite_public_keys", "authenticity_token"=>"<REMOVED>", "action"=>"update", "__save_button"=>"Save", "delete_button"=>"true"}
Fetching changes from gitolite-admin repository to /tmp/redmine_git_hosting/git-tess/gitolite-admin
Our hook is already installed
Removing gitolite key: redmine_kubitron_1350519119_123324.pub
Committing changes to gitolite-admin repository
Completed in 4453ms (View: 1, DB: 120) | 200 OK [https://tessellation.cs.berkeley.edu/redmine/my/public_keys/483]
</pre>

See the "delete_button"=>true.

**Comment by saric** [comment]
I'm sorry, my mistake
I have two different Redmine instances.
First one, with only redmine_git_hosting plugin works OK.
Problem is with second one, and I've looked at the wrong one and sent you incorrect information. 

Problem is caused probably by installation of some other plugin:

```
Ruby version              1.8.7 (i386-linux)
RubyGems version          1.3.7
Rack version              1.1.3
Rails version             2.3.14
Active Record version     2.3.14
Active Resource version   2.3.14
Action Mailer version     2.3.14
Active Support version    2.3.14
Application root          /usr/local/src/redmine-1.4.4
Environment               production
Database adapter          mysql
Database schema version   20120904060609

Redmine (Monitoring & Controlling | Monitoramento & Controle)   0.1.1
Agile dwarf plugin                                              0.0.2
Redmine Git Hosting Plugin                                      0.5.0x
Redmine Scrumbler plugin                                        1.5.0
Redmine Graphs plugin                                           0.1.0
```

I've tried to install these plugins on the first instance, in order to find which of them caused this issue.
It's "probably" redmine_scrumbler.

**Comment by kubitron** [comment]
Ok.  So you have a good bug to report to them: what is happening, I suspect, is that the errant plugin is not using the proper "play nice with others" syntax for invoking Javascript on loading of a window.  They are probably doing something like:

```
Window.onload = something;
```

instead of the proper stylized:

```
Event.observe(window, 'load', something);
```

That would make the most sense, given the behavior.  The first invocation will kill off all other handlers installed by plugins (and Redmine itself!).  Thus, in fact, you will probably have other subtle problems with Redmine caused by that plugin that you haven't noticed yet.

Glad to hear that I wasn't totally crazy!
