### ISSUE TITLE
Please make redmine_git_hosting fetch commits and other objects when adding an existing repo.

### ISSUE THREAD

**Issue by crocket** [kubitron/redmine_git_hosting#92]
When an existing gitoltie repo is added to a project via redmine_git_hosting,
I want it to fetch git objects including commits and tags.

I still think "autofetch commits" option is redundant with redmine_git_hosting's hook fetching commits.

This behavior is not existent in chiliproject nor redmine_git_hosting.

It is a feature request.

I want fetching to occur only when needed.

**Comment by kubitron** [comment]
You should really run fetch_changesets from a cron job to make sure that the gitolite config file is kept up to date (as recommended in the README). While "autofetch commits" might be redundant, it is a good idea to keep it enabled in case something goes wrong with the process (nothing is perfect).

I'll consider adding this, but it is a really low-priority addition.

**Comment by crocket** [comment]
One solution would be to create an empty repository and push branches from an existing repo to the new empty repository.
This way, if redmine_git_hosting's post-receive hook doesn't fail, you don't need "autofetch commits" option nor a cronjob for fetching commits.

By the way, this is a feature that should be implemented in chiliproject itself if it ever deserves an implementation.

Please forget about this.

**Comment by kubitron** [comment]
Incidentally--I didn't mean to close it out on you (guess I was tired last night).  We can reopen it if you like.  

I'm happy to consider it.  The issue is a bit more complex than you think, however.  I and a number of other users of this plugin have repositories that are huge and take 5 minutes to load into Redmine (assume the same issue with Chili).  This is so long that the web server times out -- consequently, the best way to load a new repo into the system is via rake from the command-line... (which doesn't time out).
